version: '3.4'

services:
  my_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_mysql_db
    ports:
      - '3306:3306'
    volumes:
      - my_volume:/var/lib/mysql
  nodeboardapp:
    image: nodeboardapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
volumes: 
  my_volume: