version: '3.4'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_development
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldata:/var/lib/mysql

  myapp:
    image: mynode
    build:
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app

volumes:
  mysqldata:
